/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NowRouteImport } from './routes/now'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRoute
  '/readme': typeof ReadmeRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRoute
  '/readme': typeof ReadmeRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRoute
  '/readme': typeof ReadmeRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/journey'
    | '/now'
    | '/projects'
    | '/readme'
    | '/skills'
    | '/terminal'
    | '/api/assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/journey'
    | '/now'
    | '/projects'
    | '/readme'
    | '/skills'
    | '/terminal'
    | '/api/assistant'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/journey'
    | '/now'
    | '/projects'
    | '/readme'
    | '/skills'
    | '/terminal'
    | '/api/assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  NowRoute: typeof NowRoute
  ProjectsRoute: typeof ProjectsRoute
  ReadmeRoute: typeof ReadmeRoute
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  NowRoute: NowRoute,
  ProjectsRoute: ProjectsRoute,
  ReadmeRoute: ReadmeRoute,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
  ApiAssistantRoute: ApiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
